export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_RESULTS = 'SEARCH_MOVIES_RESULTS';
export const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR';
export const FETCH_MOVIE_DATA = 'FETCH_MOVIE_DATA';
export const FETCH_MOVIE_DATA_RESULT = 'FETCH_MOVIE_DATA_RESULT';
export const FETCH_MOVIE_DATA_ERROR = 'FETCH_MOVIE_DATA_ERROR';